### ISSUE TITLE
Je recherche un développeur passionné

### ISSUE THREAD

**Issue by adauleu** [bloodyowl/react-higher-event#7]
Bonjour Matthias,

L'approche est un peu particulière mais je l'espère un peu plus originale.

Je suis Alban Dauleu, Consultant Manageur chez Xebia, on t'a déjà contacté par le passé (via Louis Laroche dernièrement).

Mais tout d’abord, je pense que je dois me présenter pour que tu saches qui t’écrit.

J’ai 30 ans, j’ai commencé ma carrière comme développeur 3D en 2008 et j’ai intégré Xebia il y a un plus de 2 ans.
J’ai effectué différentes missions pour des clients et au bout de 20 mois, je suis passé Consultant Manageur.

Mais Manageur c’est un rôle que j’ai en plus, mon métier n’a pas changé et aujourd'hui j’ai un profil Craftsmanship Javascript (React, Angular et NodeJS).

J’ai maintenant 8 ans d’expérience et je suis toujours développeur.

Pourquoi je te contacte ? Au sein de Xebia nous cherchons à améliorer notre métier, nous pensons que nous nous devons d’être de meilleurs développeurs, de faire des projets plus maintenables, mieux écrits et d’en être fiers.

Je t'écris une issue sur un de tes projets personnels. J'aime cet esprit et je suis impressionné par tous tes travaux sur React. Comme tu l'as compris, je suis à la recherche de mes futurs collègues, des développeurs qui ont du vécu et du recul sur leur métier pour élever le niveau de notre profession. Est-ce que ce genre de défi t’intéresse ?

Si c'est le cas, je serais ravi d’en discuter avec toi.

Tu as peut-être envie d’en savoir plus sur moi via mon profil LinkedIn : https://www.linkedin.com/in/alban-dauleu-a2137788/

Dans l’attente de te lire,
Cordialement

Alban Dauleu

**Comment by bloodyowl** [comment]
Issues are for project-related bug reports.

**Comment by jucrouzet** [comment]
THIS is huge ... ly insane.
I hope anyone passing by this gem will note the company name and blacklist them ...

**Comment by Pierstoval** [comment]
> Bonjour Matthias,
> 
> L'approche est un peu particulière mais je l'espère un peu plus originale.
> 
> Je suis Alban Dauleu, Consultant Manageur chez Xebia, on t'a déjà contacté par le passé (via Louis Laroche dernièrement).
> 
> Mais tout d’abord, je pense que je dois me présenter pour que tu saches qui t’écrit.
> 
> J’ai 30 ans, j’ai commencé ma carrière comme développeur 3D en 2008 et j’ai intégré Xebia il y a un plus de 2 ans.
> J’ai effectué différentes missions pour des clients et au bout de 20 mois, je suis passé Consultant Manageur.
> 
> Mais Manageur c’est un rôle que j’ai en plus, mon métier n’a pas changé et aujourd'hui j’ai un profil Craftsmanship Javascript (React, Angular et NodeJS).
> 
> J’ai maintenant 8 ans d’expérience et je suis toujours développeur.
> 
> Pourquoi je te contacte ? Au sein de Xebia nous cherchons à améliorer notre métier, nous pensons que nous nous devons d’être de meilleurs développeurs, de faire des projets plus maintenables, mieux écrits et d’en être fiers.
> 
> Je t'écris une issue sur un de tes projets personnels. J'aime cet esprit et je suis impressionné par tous tes travaux sur React. Comme tu l'as compris, je suis à la recherche de mes futurs collègues, des développeurs qui ont du vécu et du recul sur leur métier pour élever le niveau de notre profession. Est-ce que ce genre de défi t’intéresse ?
> 
> Si c'est le cas, je serais ravi d’en discuter avec toi.
> 
> Tu as peut-être envie d’en savoir plus sur moi via mon profil LinkedIn : https://www.linkedin.com/in/alban-dauleu-a2137788/
> 
> Dans l’attente de te lire,
> Cordialement
> 
> Alban Dauleu

You're right @jucrouzet, let's note it in the comments right here with a simple copy/paste, in case the author wants to update his comment and remove everything

:trollface:

**Comment by joe-mojo** [comment]
While you may not like the approach @jucrouzet, or find it awkward, I see no reason to blacklist anyone... You're not very open-minded and you could have understood why an experienced dev looking for competent/qualified colleague, someone with whom you would like to work...

And @Pierstoval , your childish attitude will not valuate you for anything.

Why you guys just don't explain factually, with rationale and without judging, what is isn't good in @adauleu's post ?? 

To be exemplary, I'll make the first step : 
Cons : a hiring message is kind of personal, so posting on a github issue may be not appropriate and not appreciated
Pro : for a company involved in the community, with passionate devs that take really care of software quality, this is sometime difficult to show they are not the random garbage company that send bullshit-consultants to produce poor quality code like so much other ones... so devs of that company are looking for singular way of getting in touch...

**Comment by Pierstoval** [comment]
@joe-mojo Why didn't we explained? 

Because it's obvious and common-sense that clicking the `New issue` is for creating an *issue*. If you want to hire someone, you'd better crawl all Github profiles and search for emails (which is already done by lots of bots, as I receive emails from crawlers like this).

Plus, the guy posted the exact same announcement in a lot of projects.

Github issues are here to discuss about the projects, report bugs, make projects better.

Not to spam project owners and watchers with notifications about something they certainly don't give a 💩 about.

Childish, maybe.

Pragmatic, I hope you got the point.

**Comment by joe-mojo** [comment]
> Because it's obvious and common-sense that clicking the New issue is for creating an issue. If you want to hire someone, you'd better crawl all Github profiles and search for emails (which is already done by lots of bots, as I receive emails from crawlers like this).

And what if @adauleu is not a bot and have no access to email ? 
I understand the point on issues, but what is not obvious is denigrating before explaining. This lack of assertiveness if as much unwanted as the hiring message. A childish behaviour is (for me) more blacklist prone a the public hiring offer that is... unseen to me. Wrong way ? Just explain why, because 
1) closing the issue and saying issue tracker is only for issue was sufficient
2) trying to get in touch with someone in a singular way (no bot, real dev) can be awkward, and trouble you, but you just have to say it an explain it.
3) As far as I know, the recipient just closed the issue without superfluous agressivity, so it was not calling flame war or delating behaviour. 

Now I hope that is is clear that I didn't expect any message after the issue closing, and I was not your business. I posted only because if we are fade up with total beginners that are using issue tracker as support service, etc. we won't be ok either with aggressive tiers not concerned with the business, that add useless agressivity/denigration.

Please keep peaceful and assertive in the future.

Sorry @bloodyowl for polluting your issue tracker, but I think is important to keep peace and rational and mature behaviour on public project. This is not Trump's tweetline.

**Comment by bloodyowl** [comment]
@joe-mojo given the fact recruiters have aggressive approaches (calling your personal phone, sending dozens of emails even after you told them not to) people have the liberty to personally "blacklist" a recruiter for trying in places that aren't appropriate, I know I would.
